name: Build

on:
  push:
    tags:
      - 'v*'

env:
  ENABLED_MODULES: brotli geoip2

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Build packages
        run: |
          set -ex
          docker build --build-arg ENABLED_MODULES -t buster-build - < buster.Dockerfile
          docker build --build-arg ENABLED_MODULES -t focal-build - < focal.Dockerfile
          docker cp "$(docker create buster-build):/tmp/packages/." .
          docker cp "$(docker create focal-build):/tmp/packages/." .
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload to release assets
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          url: ${{ steps.create_release.outputs.upload_url }}
        run: |
          set -ex
          url=${url%%\{*}
          for module in $ENABLED_MODULES; do
            for deb in nginx-module-"$module"_*.deb; do
              curl -f -X POST -D - \
                -H "Authorization: token $token" \
                -H 'Accept: application/vnd.github.v3+json' \
                -H 'Content-Type: application/vnd.debian.binary-package' \
                --data-binary "@$deb" \
                "$url?name=$deb"
            done
          done
