name: Build Modules

on:
  push:
    tags:
      - '**'

env:
  NGINX_VERSION: '1.23.3'
  ENABLED_MODULES: brotli headers-more

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Set Upload URL
        env:
          url: ${{ steps.create_release.outputs.upload_url }}
        run: |
          url=${url%%\{*}
          echo "UPLOAD_URL=$url" >> $GITHUB_ENV
      
      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set Up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          outputs: |
            type=image,push=false
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            UPLOAD_URL=${{ env.UPLOAD_URL }}
            ENABLED_MODULES=${{ env.ENABLED_MODULES }}
